
spring.datasource:
  url: jdbc:h2:mem:kalah;MODE=MYSQL;DB_CLOSE_DELAY=-1
  driver-class-name: org.h2.Driver

spring.h2.console:
  enabled: true
  path: /h2-console
  settings:
    web-allow-others: true

