
spring.jackson:
  serialization:
    indent-output: true

spring.mvc:
  log-request-details: true

management.server:
  port: 8088
management.endpoints.web:
  exposure.include: "*"
  base-path: /manage

#logging.level:
#  org.springframework.web.client.RestTemplate: DEBUG
