
spring.jackson:
  serialization:
    indent-output: true

spring.mvc:
  log-request-details: true

management.server:
  port: 8088
management.endpoints.web:
  exposure.include: "*"
  base-path: /manage

# to support springdoc swagger via ngrok reverse proxy
server:
  forward-headers-strategy: framework

# We intentionally disable springdoc cache, because we can access same
# server via http/https, local ip or ngrok reverse proxy
springdoc:
  cache.disabled: true

#logging.level:
#  org.springframework.web.client.RestTemplate: DEBUG
